seguridad:
    resource: "@seguridadBundle/Controller/"
    type:     annotation
    prefix:   /

futsal:
    resource: '@futsalBundle/Controller/'
    prefix:   /proyecto
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
