<?php

namespace futsalBundle\Repository;

/**
 * futsalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class futsalRepository extends \Doctrine\ORM\EntityRepository
{
}
