<?php

namespace futsalBundle\Repository;

/**
 * jornadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jornadaRepository extends \Doctrine\ORM\EntityRepository
{
}
